---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9  # vanilla image!

dependencies:
  python_interpreter:
    package_system: python39
    python_path: /usr/bin/python3.9

  ansible_core:
    package_pip: ansible==7.0.0

  ansible_runner:
    package_pip: ansible-runner==2.2.1

  galaxy: requirements.yml

additional_build_steps:
  append_base:
    - RUN yum install -y git
    - RUN curl https://packages.microsoft.com/config/rhel/7/prod.repo | tee /etc/yum.repos.d/microsoft.repo
    - RUN yum update
    - RUN yum install -y powershell
    - RUN pwsh --version
