name: Build EE image

on:
  workflow_dispatch:
  
env:
  REGISTRY_URL: ghcr.io
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install ansible builder
        run: pip install ansible-builder==3.0.0.0b1
      - name: build image
        run: ansible-builder build --tag ghcr.io/OneCyrus/ansible-test/awx-pwsh-ee:latest --container-runtime docker -f execution-environment.yml
        working-directory: execenv
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image to registry
        run: |
          docker push ghcr.io/OneCyrus/ansible-test/awx-pwsh-ee:latest
